@extends('layouts.admin')

@section('title', 'Referrals - Earn Quest')
@section('page-title', 'Referral Network')

@section('content')
<div class="space-y-6">
    <div class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-4">
        <div class="bg-white rounded-xl shadow-lg border border-gray-100 p-5">
            <p class="text-xs uppercase text-gray-500 tracking-wide">Total Referrers</p>
            <p class="text-3xl font-bold text-gray-900 mt-2">{{ number_format($overview['total_referrers']) }}</p>
            <p class="text-xs text-gray-500 mt-2">Members who have invited at least one referral.</p>
        </div>
        <div class="bg-white rounded-xl shadow-lg border border-gray-100 p-5">
            <p class="text-xs uppercase text-gray-500 tracking-wide">Total Referrals</p>
            <p class="text-3xl font-bold text-gray-900 mt-2">{{ number_format($overview['total_referrals']) }}</p>
            <p class="text-xs text-gray-500 mt-2">All members who were referred into the platform.</p>
        </div>
        <div class="bg-white rounded-xl shadow-lg border border-gray-100 p-5">
            <p class="text-xs uppercase text-gray-500 tracking-wide">Active Referrals</p>
            <p class="text-3xl font-bold text-emerald-600 mt-2">{{ number_format($overview['active_referrals']) }}</p>
            <p class="text-xs text-gray-500 mt-2">Referred users who have deposited and are eligible for payouts.</p>
        </div>
        <div class="bg-white rounded-xl shadow-lg border border-gray-100 p-5">
            <p class="text-xs uppercase text-gray-500 tracking-wide">Referral Deposits</p>
            <p class="text-3xl font-bold text-blue-600 mt-2">${{ number_format($overview['total_referral_deposits'], 2) }}</p>
            <p class="text-xs text-gray-500 mt-2">Total deposit volume generated by referrals.</p>
        </div>
    </div>

    <div class="bg-white rounded-xl shadow-lg border border-gray-100 p-6">
        <div class="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4 mb-6">
            <div>
                <h3 class="text-lg font-semibold text-gray-900">Referrer Breakdown</h3>
                <p class="text-sm text-gray-600">Drill into each referrer to review their network performance.</p>
            </div>
            <div class="text-sm text-gray-500 bg-gray-50 border border-gray-200 rounded-lg px-4 py-2">
                Total Referral Withdrawals: <span class="font-semibold text-gray-900">${{ number_format($overview['total_referral_withdrawals'], 2) }}</span>
            </div>
        </div>

        @forelse($referrers as $referrer)
            @php
                $referrals = $referrer->referrals;
                $activeReferrals = $referrals->where('has_deposited', true);
                $referralDepositSum = $referrals->sum(fn ($ref) => $ref->deposits->sum('amount'));
                $referralWithdrawalSum = $referrals->sum(fn ($ref) => $ref->withdrawals->sum('amount'));
                $packageBreakdown = $referrals->groupBy('investment_package');
            @endphp

            <div class="border border-gray-200 rounded-2xl mb-6 overflow-hidden">
                <div class="bg-gradient-to-r from-indigo-500 via-blue-500 to-purple-500 px-6 py-5 text-white flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4">
                    <div>
                        <h4 class="text-xl font-bold flex items-center gap-3">
                            <span class="inline-flex items-center justify-center w-10 h-10 rounded-xl bg-white/20 text-white text-lg">
                                <i class="fas fa-user-friends"></i>
                            </span>
                            {{ $referrer->name }}
                        </h4>
                        <p class="text-sm text-blue-100">{{ $referrer->email }}</p>
                    </div>
                    <div class="grid grid-cols-2 md:grid-cols-4 gap-3 text-sm">
                        <div class="bg-white/15 rounded-lg px-4 py-2 text-center">
                            <p class="text-blue-100 text-xs uppercase tracking-wide">Total Referrals</p>
                            <p class="text-xl font-semibold">{{ $referrals->count() }}</p>
                        </div>
                        <div class="bg-white/15 rounded-lg px-4 py-2 text-center">
                            <p class="text-blue-100 text-xs uppercase tracking-wide">Active Referrals</p>
                            <p class="text-xl font-semibold">{{ $activeReferrals->count() }}</p>
                        </div>
                        <div class="bg-white/15 rounded-lg px-4 py-2 text-center">
                            <p class="text-blue-100 text-xs uppercase tracking-wide">Referral Deposits</p>
                            <p class="text-xl font-semibold">${{ number_format($referralDepositSum, 2) }}</p>
                        </div>
                        <div class="bg-white/15 rounded-lg px-4 py-2 text-center">
                            <p class="text-blue-100 text-xs uppercase tracking-wide">Referral Withdrawals</p>
                            <p class="text-xl font-semibold">${{ number_format($referralWithdrawalSum, 2) }}</p>
                        </div>
                    </div>
                </div>

                <div class="px-6 py-5 bg-white">
                    <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
                        <div class="bg-gray-50 border border-gray-200 rounded-lg p-4">
                            <h5 class="text-sm font-semibold text-gray-700 mb-2">Referral Package Mix</h5>
                            <div class="space-y-2 text-sm text-gray-600">
                                @foreach($packages as $code => $package)
                                    <div class="flex items-center justify-between">
                                        <span>{{ $package['name'] }}</span>
                                        <span class="font-semibold text-gray-900">{{ $packageBreakdown->get($code, collect())->count() }}</span>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                        <div class="bg-gray-50 border border-gray-200 rounded-lg p-4">
                            <h5 class="text-sm font-semibold text-gray-700 mb-2">Referrer Snapshot</h5>
                            <ul class="text-sm text-gray-600 space-y-2">
                                <li><span class="font-medium text-gray-800">Joined:</span> {{ optional($referrer->created_at)->format('M d, Y') }}</li>
                                <li><span class="font-medium text-gray-800">Total Balance:</span> ${{ number_format($referrer->balance, 2) }}</li>
                                <li><span class="font-medium text-gray-800">Points:</span> {{ number_format($referrer->points ?? 0) }}</li>
                                <li><span class="font-medium text-gray-800">Referral Link:</span> <span class="font-mono text-xs break-all">{{ route('register', ['ref' => $referrer->referral_code]) }}</span></li>
                            </ul>
                        </div>
                    </div>

                    <div class="overflow-x-auto">
                        <table class="min-w-full text-sm">
                            <thead>
                                <tr class="text-left text-xs uppercase text-gray-500">
                                    <th class="pb-3">Referral</th>
                                    <th class="pb-3">Package</th>
                                    <th class="pb-3">Deposited</th>
                                    <th class="pb-3">Withdrawn</th>
                                    <th class="pb-3">Status</th>
                                    <th class="pb-3">Joined</th>
                                </tr>
                            </thead>
                            <tbody class="divide-y divide-gray-100 text-gray-900">
                                @forelse($referrals as $referral)
                                    @php
                                        $packageConfig = $referral->investment_package ? ($packages[$referral->investment_package] ?? null) : null;
                                        $refDepositSum = $referral->deposits->sum('amount');
                                        $refWithdrawalSum = $referral->withdrawals->sum('amount');
                                    @endphp
                                    <tr class="hover:bg-gray-50 transition-colors">
                                        <td class="py-3">
                                            <div class="flex flex-col">
                                                <span class="font-semibold">{{ $referral->name }}</span>
                                                <span class="text-xs text-gray-500">{{ $referral->email }}</span>
                                            </div>
                                        </td>
                                        <td class="py-3">
                                            <span class="font-medium">{{ $packageConfig['name'] ?? '—' }}</span>
                                            @if($packageConfig)
                                                <span class="block text-xs text-gray-500">${{ number_format($packageConfig['deposit_amount'], 2) }}</span>
                                            @endif
                                        </td>
                                        <td class="py-3">${{ number_format($refDepositSum, 2) }}</td>
                                        <td class="py-3">${{ number_format($refWithdrawalSum, 2) }}</td>
                                        <td class="py-3">
                                            <span class="inline-flex items-center px-2 py-1 rounded-full text-xs {{ $referral->has_deposited ? 'bg-emerald-100 text-emerald-700' : 'bg-yellow-100 text-yellow-700' }}">
                                                {{ $referral->has_deposited ? 'Active' : 'Pending Deposit' }}
                                            </span>
                                        </td>
                                        <td class="py-3 text-xs text-gray-500">{{ optional($referral->created_at)->format('M d, Y') }}</td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="6" class="py-4 text-center text-sm text-gray-500">No referrals recorded for this member yet.</td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        @empty
            <div class="py-10 text-center text-gray-500 bg-gray-50 border border-dashed border-gray-200 rounded-xl">
                <i class="fas fa-users-slash text-3xl mb-3 text-gray-400"></i>
                <p class="text-sm">No referral activity has been recorded yet.</p>
            </div>
        @endforelse

        <div class="mt-6">
            {{ $referrers->links() }}
        </div>
    </div>
</div>
@endsection

